nn_genie_maintenance_homepage:
    path:     /
    defaults: { _controller: NNGenieMaintenanceBundle:Default:index }

nn_genie_maintenance_pannes:
    pattern: /pannes
    defaults: { _controller: NNGenieMaintenanceBundle:Panne:pannes }
    options:
        expose: true


nn_genie_maintenance_panne_new:
    pattern: /new-panne
    defaults: { _controller: NNGenieMaintenanceBundle:Panne:new }
    options:
        expose: true
        
nn_genie_maintenance_panne_edit:
    pattern: /edit-panne/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Panne:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_panne_delete:
    pattern: /delete-panne/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Panne:delete }
    options:
        expose: true
        

nn_genie_maintenance_pieces:
    pattern: /pieces
    defaults: { _controller: NNGenieMaintenanceBundle:Piece:pieces }
    options:
        expose: true


nn_genie_maintenance_piece_new:
    pattern: /new-piece
    defaults: { _controller: NNGenieMaintenanceBundle:Piece:new }
    options:
        expose: true
        
nn_genie_maintenance_piece_edit:
    pattern: /edit-piece/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Piece:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_piece_delete:
    pattern: /delete-piece/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Piece:delete }
    options:
        expose: true
        
nn_genie_maintenance_operations:
    pattern: /operations
    defaults: { _controller: NNGenieMaintenanceBundle:Operation:operations }
    options:
        expose: true


nn_genie_maintenance_operation_new:
    pattern: /new-operation
    defaults: { _controller: NNGenieMaintenanceBundle:Operation:new }
    options:
        expose: true
        
nn_genie_maintenance_operation_edit:
    pattern: /edit-operation/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Operation:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_operation_delete:
    pattern: /delete-operation/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Operation:delete }
    options:
        expose: true
        
nn_genie_maintenance_produits:
    pattern: /produits
    defaults: { _controller: NNGenieMaintenanceBundle:Produit:produits }
    options:
        expose: true


nn_genie_maintenance_produit_new:
    pattern: /new-produit
    defaults: { _controller: NNGenieMaintenanceBundle:Produit:new }
    options:
        expose: true
        
nn_genie_maintenance_produit_edit:
    pattern: /edit-produit/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Produit:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_produit_delete:
    pattern: /delete-produit/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Produit:delete }
    options:
        expose: true

nn_genie_maintenance_procedes:
    pattern: /procedes
    defaults: { _controller: NNGenieMaintenanceBundle:Procede:procedes }
    options:
        expose: true


nn_genie_maintenance_procede_new:
    pattern: /new-procede
    defaults: { _controller: NNGenieMaintenanceBundle:Procede:new }
    options:
        expose: true
        
nn_genie_maintenance_procede_edit:
    pattern: /edit-procede/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Procede:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_procede_delete:
    pattern: /delete-procede/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Procede:delete }
    options:
        expose: true
        
nn_genie_maintenance_questions:
    pattern: /questions
    defaults: { _controller: NNGenieMaintenanceBundle:Question:questions }
    options:
        expose: true


nn_genie_maintenance_question_new:
    pattern: /new-question
    defaults: { _controller: NNGenieMaintenanceBundle:Question:new }
    options:
        expose: true
        
nn_genie_maintenance_question_edit:
    pattern: /edit-question/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Question:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_question_delete:
    pattern: /delete-question/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Question:delete }
    options:
        expose: true
        
nn_genie_maintenance_tests:
    pattern: /tests
    defaults: { _controller: NNGenieMaintenanceBundle:Test:tests }
    options:
        expose: true


nn_genie_maintenance_test_new:
    pattern: /new-test
    defaults: { _controller: NNGenieMaintenanceBundle:Test:new }
    options:
        expose: true
        
nn_genie_maintenance_test_edit:
    pattern: /edit-test/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Test:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_test_delete:
    pattern: /delete-test/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Test:delete }
    options:
        expose: true
        
nn_genie_maintenance_controlesmatinaux:
    pattern: /controles-matinaux
    defaults: { _controller: NNGenieMaintenanceBundle:Controlematinal:controlesmatinaux }
    options:
        expose: true


nn_genie_maintenance_controlematinal_new:
    pattern: /new-controle-matinal
    defaults: { _controller: NNGenieMaintenanceBundle:Controlematinal:new }
    options:
        expose: true
        
nn_genie_maintenance_controlematinal_edit:
    pattern: /edit-controle-matinal/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Controlematinal:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_controlematinal_delete:
    pattern: /delete-controle-matinal/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Controlematinal:delete }
    options:
        expose: true
        
nn_genie_maintenance_entretiensperiodiques:
    pattern: /entretiens-periodiques
    defaults: { _controller: NNGenieMaintenanceBundle:Entretienperiodique:entretiensperiodiques }
    options:
        expose: true


nn_genie_maintenance_entretienperiodique_new:
    pattern: /new-entretien-periodique
    defaults: { _controller: NNGenieMaintenanceBundle:Entretienperiodique:new }
    options:
        expose: true
        
nn_genie_maintenance_entretienperiodique_edit:
    pattern: /edit-entretien-periodique/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Entretienperiodique:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_entretienperiodique_delete:
    pattern: /delete-entretien-periodique/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Entretienperiodique:delete }
    options:
        expose: true
        
nn_genie_maintenance_fournisseurspieces:
    pattern: /fournisseurs-pieces
    defaults: { _controller: NNGenieMaintenanceBundle:Fournisseurpiece:fournisseurspieces }
    options:
        expose: true


nn_genie_maintenance_fournisseurpiece_new:
    pattern: /new-fournisseur-piece
    defaults: { _controller: NNGenieMaintenanceBundle:Fournisseurpiece:new }
    options:
        expose: true
        
nn_genie_maintenance_fournisseurpiece_edit:
    pattern: /edit-fournisseur-piece/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Fournisseurpiece:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_fournisseurpiece_delete:
    pattern: /delete-fournisseur-piece/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Fournisseurpiece:delete }
    options:
        expose: true
        
nn_genie_maintenance_typereglages:
    pattern: /types-reglage   
    defaults: { _controller: NNGenieMaintenanceBundle:Typereglage:typereglages }
    options:
        expose: true

nn_genie_maintenance_typereglage_new:
    pattern: /new-type-reglage
    defaults: { _controller: NNGenieMaintenanceBundle:Typereglage:new }
    options:
        expose: true
        
nn_genie_maintenance_typereglage_edit:
    pattern: /edit-type-reglage/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Typereglage:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_typereglage_delete:
    pattern: /delete-type-reglage/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Typereglage:delete }
    options:
        expose: true
        
nn_genie_maintenance_reglages:
    pattern: /reglages
    defaults: { _controller: NNGenieMaintenanceBundle:Reglage:reglages }
    options:
        expose: true


nn_genie_maintenance_reglage_new:
    pattern: /new-reglage
    defaults: { _controller: NNGenieMaintenanceBundle:Reglage:new }
    options:
        expose: true
        
nn_genie_maintenance_reglage_edit:
    pattern: /edit-reglage/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Reglage:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_reglage_delete:
    pattern: /delete-reglage/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Reglage:delete }
    options:
        expose: true
        
nn_genie_maintenance_propretes:
    pattern: /propretes
    defaults: { _controller: NNGenieMaintenanceBundle:Proprete:propretes }
    options:
        expose: true


nn_genie_maintenance_proprete_new:
    pattern: /new-proprete
    defaults: { _controller: NNGenieMaintenanceBundle:Proprete:new }
    options:
        expose: true
        
nn_genie_maintenance_proprete_edit:
    pattern: /edit-proprete/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Proprete:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_proprete_delete:
    pattern: /delete-proprete/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Proprete:delete }
    options:
        expose: true
        
nn_genie_maintenance_typepropretes:
    pattern: /types-proprete   
    defaults: { _controller: NNGenieMaintenanceBundle:Typeproprete:typepropretes }
    options:
        expose: true

nn_genie_maintenance_typeproprete_new:
    pattern: /new-type-proprete
    defaults: { _controller: NNGenieMaintenanceBundle:Typeproprete:new }
    options:
        expose: true
        
nn_genie_maintenance_typeproprete_edit:
    pattern: /edit-type-proprete/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Typeproprete:edit }
    options:
        expose: true
        
        
nn_genie_maintenance_typeproprete_delete:
    pattern: /delete-type-proprete/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Typeproprete:delete }
    options:
        expose: true

nn_genie_maintenance_revisions:
    pattern: /revisions
    defaults: { _controller: NNGenieMaintenanceBundle:Revision:revisions }
    options:
        expose: true


nn_genie_maintenance_revision_new:
    pattern: /new-revision
    defaults: { _controller: NNGenieMaintenanceBundle:Revision:new }
    options:
        expose: true
        
nn_genie_maintenance_revision_edit:
    pattern: /edit-revision/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Revision:edit }
    options:
        expose: true        
        
nn_genie_maintenance_revision_delete:
    pattern: /delete-revision/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Revision:delete }
    options:
        expose: true
        
nn_genie_maintenance_anomalies:
    pattern: /anomalies
    defaults: { _controller: NNGenieMaintenanceBundle:Anomalie:anomalies }
    options:
        expose: true


nn_genie_maintenance_anomalie_new:
    pattern: /new-anomalie
    defaults: { _controller: NNGenieMaintenanceBundle:Anomalie:new }
    options:
        expose: true
        
nn_genie_maintenance_anomalie_edit:
    pattern: /edit-anomalie/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Anomalie:edit }
    options:
        expose: true        
        
nn_genie_maintenance_anomalie_delete:
    pattern: /delete-anomalie/{id}
    defaults: { _controller: NNGenieMaintenanceBundle:Anomalie:delete }
    options:
        expose: true
        
nn_genie_maintenance_results_search:
    pattern: /results-search
    defaults: { _controller: NNGenieMaintenanceBundle:Maintenance:getResultsSearch }
    options:
        expose: true