nn_genie_formation:
    resource: "@NNGenieFormationBundle/Resources/config/routing.yml"
    prefix:   /Formation

nn_genie_exploitation:
    resource: "@NNGenieExploitationBundle/Resources/config/routing.yml"
    prefix:   /Exploitation
nn_genie_maintenance:
    resource: "@NNGenieMaintenanceBundle/Resources/config/routing.yml"
    prefix:   /maintenance

nn_genie_infos_mat_materiel:
    resource: "@NNGenieInfosMatBundle/Controller/MaterielController.php"
    type:     annotation

nn_genie_user:
    resource: "@NNGenieUserBundle/Resources/config/routing.yml"
    prefix:   /

nn_genie_infos_mat:
    resource: "@NNGenieInfosMatBundle/Resources/config/routing.yml"
    prefix:   /informations-generales-materiels

nn_genie_infos_mat_user:
    resource: "@NNGenieUserBundle/Controller/UserController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
