nn_genie_infos_mat_homepage:
    path:     /
    defaults: { _controller: NNGenieInfosMatBundle:Default:index }

nn_genie_infos_mat_commentaire_index:
    path:     /commentaire/index/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Commentaire:index }
    requirements:
        id: \d+        

nn_genie_infos_mat_commentaire_new:
    path:     /commentaire/new/{materiel_id}/{user_id}
    defaults: { _controller: NNGenieInfosMatBundle:Commentaire:new }

nn_genie_infos_mat_commentaire_view:
    path:     /commentaire/view/{materiel_id}/{user_id}
    defaults: { _controller: NNGenieInfosMatBundle:Commentaire:view }

nn_genie_infos_mat_commentaire_delete:
    path:     /commentaire/delete/{commentaire_id}/{materiel_id}
    defaults: { _controller: NNGenieInfosMatBundle:Commentaire:delete }
    
nn_genie_infos_mat_commentaire_edit:
    path:     /commentaire/edit/{commentaire_id}/{materiel_id}
    defaults: { _controller: NNGenieInfosMatBundle:Commentaire:edit }
nn_genie_infos_mat_disponibilite_index:
    path:     /disponibilite/index
    defaults: { _controller: NNGenieInfosMatBundle:Disponibilite:index }

nn_genie_infos_mat_disponibilite_new:
    path:     /disponibilite/new
    defaults: { _controller: NNGenieInfosMatBundle:Disponibilite:new }

nn_genie_infos_mat_disponibilite_edit:
    path:     /disponibilite/edit/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Disponibilite:edit }
    requirements:
        id: \d+
nn_genie_infos_mat_disponibilite_delete:
    path:     /disponibilite/delete/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Disponibilite:delete }

nn_genie_infos_mat_disponibilite_view:
    path:     /disponibilite/view/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Disponibilite:view }
    requirements:
        id: \d+
nn_genie_infos_mat_disponibilitemateriel_index:
    path:     /disponibilitemateriel/index
    defaults: { _controller: NNGenieInfosMatBundle:Disponibilitemateriel:index }

nn_genie_infos_mat_disponibilitemateriel_view:
    path:     /disponibilitemateriel/view/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Disponibilitemateriel:view }

nn_genie_infos_mat_disponibilitemateriel_new:
    path:     /disponibilitemateriel/new/{materiel_id}/{disponibilite_id}
    defaults: { _controller: NNGenieInfosMatBundle:Disponibilitemateriel:new }

nn_genie_infos_mat_disponibilitemateriel_edit:
    path:     /disponibilitemateriel/edit
    defaults: { _controller: NNGenieInfosMatBundle:Disponibilitemateriel:edit }

nn_genie_infos_mat_disponibilitemateriel_delete:
    path:     /disponibilitemateriel/delete
    defaults: { _controller: NNGenieInfosMatBundle:Disponibilitemateriel:delete }

nn_genie_infos_mat_etat_index:
    path:     /etat/index
    defaults: { _controller: NNGenieInfosMatBundle:Etat:index }

nn_genie_infos_mat_etat_view:
    path:     /etat/view/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Etat:view }
    requirements:
        id: \d+
nn_genie_infos_mat_etat_new:
    path:     /etat/new
    defaults: { _controller: NNGenieInfosMatBundle:Etat:new }

nn_genie_infos_mat_etat_edit:
    path:     /etat/edit/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Etat:edit }
    requirements:
        id: \d+
        
nn_genie_infos_mat_etat_delete:
    path:     /etat/delete/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Etat:delete }
    requirements:
        id: \d+
        
nn_genie_infos_mat_famille_index:
    path:     /famille/index
    defaults: { _controller: NNGenieInfosMatBundle:Famille:index }

nn_genie_infos_mat_famille_view:
    path:     /famille/view/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Famille:view }
    requirements:
        id: \d+

nn_genie_infos_mat_famille_new:
    path:     /famille/new
    defaults: { _controller: NNGenieInfosMatBundle:Famille:new }

nn_genie_infos_mat_famille_edit:
    path:     /famille/edit/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Famille:edit }
    requirements:
        id: \d+

nn_genie_infos_mat_famille_delete:
    path:     /famille/delete/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Famille:delete }
    requirements:
        id: \d+

nn_genie_infos_mat_adresse_index:
    path:     /adresse/index
    defaults: { _controller: NNGenieInfosMatBundle:Adresse:index }

nn_genie_infos_mat_adresse_view:
    path:     /adresse/view/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Adresse:view }
    requirements:
        id: \d+

nn_genie_infos_mat_adresse_new:
    path:     /adresse/new
    defaults: { _controller: NNGenieInfosMatBundle:Adresse:new }

nn_genie_infos_mat_adresse_edit:
    path:     /adresse/edit/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Adresse:edit }
    requirements:
        id: \d+

nn_genie_infos_mat_adresse_delete:
    path:     /adresse/delete/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Adresse:delete }
    requirements:
        id: \d+

    defaults: { _controller: NNGenieInfosMatBundle:Materiel:index }

nn_genie_infos_mat_accueil:
    pattern: /accueil
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:accueil }
    options:
        expose: true

nn_genie_infos_mat_materiels:
    pattern: /materiels
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:materiels }
    options:
        expose: true

nn_genie_infos_mat_materiel_filtre:
    pattern: /filtre-materiels
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:filtremateriel }
    options:
        expose: true

nn_genie_infos_mat_materiel_new:
    pattern: /new-materiel
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:new }
    options:
        expose: true
        
nn_genie_infos_mat_materiel_edit:
    pattern: /edit-materiel/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:edit }
    options:
        expose: true
        
nn_genie_infos_mat_materiel_delete:
    pattern: /delete-materiel/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:delete }
    options:
        expose: true

nn_genie_infos_mat_materiel_detail:
    pattern: /detail-materiel/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:detail }
    options:
        expose: true

nn_genie_infos_mat_materiel_edit_main_image:
    pattern: /edit-main-image/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:editMainImage }
    options:
        expose: true

nn_genie_infos_mat_types:
    pattern: /types
    defaults: { _controller: NNGenieInfosMatBundle:Type:types }
    options:
        expose: true
        
nn_genie_infos_mat_type_new:
    pattern: /new-type
    defaults: { _controller: NNGenieInfosMatBundle:Type:new }
    options:
        expose: true
        
nn_genie_infos_mat_type_edit:
    pattern: /edit-type/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Type:edit }
    options:
        expose: true
        
nn_genie_infos_mat_type_delete:
    pattern: /delete-type/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Type:delete }
    options:
        expose: true


nn_genie_infos_mat_classesmateriel:
    pattern: /classes-materiel
    defaults: { _controller: NNGenieInfosMatBundle:Classemateriel:classesmateriel }
    options:
        expose: true

nn_genie_infos_mat_classemateriel_new:
    pattern: /new-classe-materiel
    defaults: { _controller: NNGenieInfosMatBundle:Classemateriel:new }
    options:
        expose: true
        
nn_genie_infos_mat_classemateriel_edit:
    pattern: /edit-classe-materiel/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Classemateriel:edit }
    options:
        expose: true
        
        
nn_genie_infos_mat_classemateriel_delete:
    pattern: /delete-classe-materiel/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Classemateriel:delete }
    options:
        expose: true
        
nn_genie_infos_mat_genres:
    pattern: /genres
    defaults: { _controller: NNGenieInfosMatBundle:Genre:genres }
    options:
        expose: true

nn_genie_infos_mat_genre_new:
    pattern: /new-genre
    defaults: { _controller: NNGenieInfosMatBundle:Genre:new }
    options:
        expose: true
        
nn_genie_infos_mat_genre_edit:
    pattern: /edit-genre/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Genre:edit }
    options:
        expose: true
        
nn_genie_infos_mat_genre_delete:
    pattern: /delete-genre/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Genre:delete }
    options:
        expose: true

nn_genie_infos_mat_proprietaires:
    pattern: /proprietaires
    defaults: { _controller: NNGenieInfosMatBundle:Proprietaire:proprietaires }
    options:
        expose: true

nn_genie_infos_mat_proprietaire_new:
    pattern: /new-proprietaire
    defaults: { _controller: NNGenieInfosMatBundle:Proprietaire:new }
    options:
        expose: true
        
nn_genie_infos_mat_proprietaire_edit:
    pattern: /edit-proprietaire/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Proprietaire:edit }
    options:
        expose: true
        
nn_genie_infos_mat_proprietaire_delete:
    pattern: /delete-proprietaire/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Proprietaire:delete }
    options:
        expose: true

nn_genie_infos_mat_marques:
    pattern: /marques
    defaults: { _controller: NNGenieInfosMatBundle:Marque:marques }
    options:
        expose: true

nn_genie_infos_mat_marque_new:
    pattern: /new-marque
    defaults: { _controller: NNGenieInfosMatBundle:Marque:new }
    options:
        expose: true
        
nn_genie_infos_mat_marque_edit:
    pattern: /edit-marque/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Marque:edit }
    options:
        expose: true
        
nn_genie_infos_mat_marque_delete:
    pattern: /delete-marque/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Marque:delete }
    options:
        expose: true

nn_genie_infos_mat_fournisseurs:
    pattern: /fournisseurs
    defaults: { _controller: NNGenieInfosMatBundle:Fournisseur:fournisseurs }
    options:
        expose: true

nn_genie_infos_mat_fournisseur_new:
    pattern: /new-fournisseur
    defaults: { _controller: NNGenieInfosMatBundle:Fournisseur:new }
    options:
        expose: true
        
nn_genie_infos_mat_fournisseur_edit:
    pattern: /edit-fournisseur/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Fournisseur:edit }
    options:
        expose: true
        
nn_genie_infos_mat_fournisseur_delete:
    pattern: /delete-fournisseur/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Fournisseur:delete }
    options:
        expose: true

nn_genie_infos_mat_images:
    pattern: /images/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Image:images }
    options:
        expose: true

nn_genie_infos_mat_image_new:
    pattern: /new-image/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Image:new }
    options:
        expose: true
        
nn_genie_infos_mat_image_edit:
    pattern: /edit-image/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Image:edit }
    options:
        expose: true
        
nn_genie_infos_mat_image_delete:
    pattern: /delete-image/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Image:delete }
    options:
        expose: true
