nn_genie_infos_mat_homepage:
    path:     /
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:index }

nn_genie_infos_mat_accueil:
    pattern: /accueil
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:accueil }
    options:
        expose: true

nn_genie_infos_mat_materiels:
    pattern: /materiels
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:materiels }
    options:
        expose: true
        
nn_genie_infos_mat_materiel_new:
    pattern: /new-materiel
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:new }
    options:
        expose: true
        
nn_genie_infos_mat_materiel_edit:
    pattern: /edit-materiel/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:edit }
    options:
        expose: true
        
nn_genie_infos_mat_materiel_delete:
    pattern: /delete-materiel/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Materiel:delete }
    options:
        expose: true

nn_genie_infos_mat_types:
    pattern: /types
    defaults: { _controller: NNGenieInfosMatBundle:Type:types }
    options:
        expose: true
        
nn_genie_infos_mat_type_new:
    pattern: /new-type
    defaults: { _controller: NNGenieInfosMatBundle:Type:new }
    options:
        expose: true
        
nn_genie_infos_mat_type_edit:
    pattern: /edit-type/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Type:edit }
    options:
        expose: true
        
nn_genie_infos_mat_type_delete:
    pattern: /delete-type/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Type:delete }
    options:
        expose: true


nn_genie_infos_mat_classesmateriel:
    pattern: /classes-materiel
    defaults: { _controller: NNGenieInfosMatBundle:Classemateriel:classesmateriel }
    options:
        expose: true

nn_genie_infos_mat_classemateriel_new:
    pattern: /new-classe-materiel
    defaults: { _controller: NNGenieInfosMatBundle:Classemateriel:new }
    options:
        expose: true
        
nn_genie_infos_mat_classemateriel_edit:
    pattern: /edit-classe-materiel/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Classemateriel:edit }
    options:
        expose: true
        
        
nn_genie_infos_mat_classemateriel_delete:
    pattern: /delete-classe-materiel/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Classemateriel:delete }
    options:
        expose: true
        
nn_genie_infos_mat_genres:
    pattern: /genres
    defaults: { _controller: NNGenieInfosMatBundle:Genre:genres }
    options:
        expose: true

nn_genie_infos_mat_genre_new:
    pattern: /new-genre
    defaults: { _controller: NNGenieInfosMatBundle:Genre:new }
    options:
        expose: true
        
nn_genie_infos_mat_genre_edit:
    pattern: /edit-genre/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Genre:edit }
    options:
        expose: true
        
nn_genie_infos_mat_genre_delete:
    pattern: /delete-genre/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Genre:delete }
    options:
        expose: true

nn_genie_infos_mat_proprietaires:
    pattern: /proprietaires
    defaults: { _controller: NNGenieInfosMatBundle:Proprietaire:proprietaires }
    options:
        expose: true

nn_genie_infos_mat_proprietaire_new:
    pattern: /new-proprietaire
    defaults: { _controller: NNGenieInfosMatBundle:Proprietaire:new }
    options:
        expose: true
        
nn_genie_infos_mat_proprietaire_edit:
    pattern: /edit-proprietaire/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Proprietaire:edit }
    options:
        expose: true
        
nn_genie_infos_mat_proprietaire_delete:
    pattern: /delete-proprietaire/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Proprietaire:delete }
    options:
        expose: true

nn_genie_infos_mat_marques:
    pattern: /marques
    defaults: { _controller: NNGenieInfosMatBundle:Marque:marques }
    options:
        expose: true

nn_genie_infos_mat_marque_new:
    pattern: /new-marque
    defaults: { _controller: NNGenieInfosMatBundle:Marque:new }
    options:
        expose: true
        
nn_genie_infos_mat_marque_edit:
    pattern: /edit-marque/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Marque:edit }
    options:
        expose: true
        
nn_genie_infos_mat_marque_delete:
    pattern: /delete-marque/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Marque:delete }
    options:
        expose: true

nn_genie_infos_mat_fournisseurs:
    pattern: /fournisseurs
    defaults: { _controller: NNGenieInfosMatBundle:Fournisseur:fournisseurs }
    options:
        expose: true

nn_genie_infos_mat_fournisseur_new:
    pattern: /new-fournisseur
    defaults: { _controller: NNGenieInfosMatBundle:Fournisseur:new }
    options:
        expose: true
        
nn_genie_infos_mat_fournisseur_edit:
    pattern: /edit-fournisseur/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Fournisseur:edit }
    options:
        expose: true
        
nn_genie_infos_mat_fournisseur_delete:
    pattern: /delete-fournisseur/{id}
    defaults: { _controller: NNGenieInfosMatBundle:Fournisseur:delete }
    options:
        expose: true