nn_genie_exploitation_homepage:
    path:     /accueil-admin
    defaults: { _controller: NNGenieExploitationBundle:Default:index }
nn_genie_exploitation_add_qualification:
    path:     /new-qualification
    defaults: { _controller: NNGenieExploitationBundle:Qualification:add }
    options:
        expose: true
nn_genie_exploitation_view_qualification:
    pattern: /qualifications
    defaults: { _controller: NNGenieExploitationBundle:Qualification:getAll }
    options:
        expose: true
nn_genie_exploitation_delete_qualification:
    pattern: /delete-qualification/{id}
    defaults: { _controller: NNGenieExploitationBundle:Qualification:delete }
    options:
        expose: true
nn_genie_exploitation_edit_qualification:
    pattern: /edit-qualification/{id}
    defaults: { _controller: NNGenieExploitationBundle:Qualification:edit }
    options:
        expose: true
nn_genie_exploitation_add_typeexploitation:
    path:     /new-typexploitation
    defaults: { _controller: NNGenieExploitationBundle:TypeExploitation:add }
    options:
        expose: true
nn_genie_exploitation_view_typeexploitation:
    pattern: /typexploitations
    defaults: { _controller: NNGenieExploitationBundle:TypeExploitation:getAll }
    options:
        expose: true
nn_genie_exploitation_delete_typexploitation:
    pattern: /delete-typexploitation/{id}
    defaults: { _controller: NNGenieExploitationBundle:TypeExploitation:delete }
    options:
        expose: true
nn_genie_exploitation_edit_typexploitation:
    pattern: /edit-typexploitation/{id}
    defaults: { _controller: NNGenieExploitationBundle:TypeExploitation:edit }
    options:
        expose: true
nn_genie_exploitation_add_specialite:
    path:     /new-specialite
    defaults: { _controller: NNGenieExploitationBundle:Specialite:add }
    options:
        expose: true
nn_genie_exploitation_view_specialite:
    pattern: /specialites
    defaults: { _controller: NNGenieExploitationBundle:Specialite:getAll }
    options:
        expose: true
nn_genie_exploitation_delete_specialite:
    pattern: /delete-specialite/{id}
    defaults: { _controller: NNGenieExploitationBundle:Specialite:delete }
    options:
        expose: true
nn_genie_exploitation_edit_specialite:
    pattern: /edit-specialite/{id}
    defaults: { _controller: NNGenieExploitationBundle:Specialite:edit }
    options:
        expose: true
nn_genie_exploitation_add_employeur:
    path:     /new-employeur
    defaults: { _controller: NNGenieExploitationBundle:Employeur:add }
    options:
        expose: true
nn_genie_exploitation_view_employeur:
    pattern: /employeurs
    defaults: { _controller: NNGenieExploitationBundle:Employeur:getAll }
    options:
        expose: true
nn_genie_exploitation_delete_employeur:
    pattern: /delete-employeur/{id}
    defaults: { _controller: NNGenieExploitationBundle:Employeur:delete }
    options:
        expose: true
nn_genie_exploitation_edit_employeur:
    pattern: /edit-employeur/{id}
    defaults: { _controller: NNGenieExploitationBundle:Employeur:edit }
    options:
        expose: true
nn_genie_exploitation_add_historique:
    path:     /new-historique
    defaults: { _controller: NNGenieExploitationBundle:Historique:add }
    options:
        expose: true
nn_genie_exploitation_view_historique:
    pattern: /historiques
    defaults: { _controller: NNGenieExploitationBundle:Historique:getAll }
    options:
        expose: true
nn_genie_exploitation_delete_historique:
    pattern: /delete-historique/{id}
    defaults: { _controller: NNGenieExploitationBundle:Historique:delete }
    options:
        expose: true
nn_genie_exploitation_edit_historique:
    pattern: /edit-historique/{id}
    defaults: { _controller: NNGenieExploitationBundle:Historique:edit }
    options:
        expose: true
nn_genie_exploitation_add_polyvalence:
    path:     /new-polyvalence
    defaults: { _controller: NNGenieExploitationBundle:Polyvalence:add }
    options:
        expose: true
nn_genie_exploitation_view_polyvalence:
    pattern: /polyvalences
    defaults: { _controller: NNGenieExploitationBundle:Polyvalence:getAll }
    options:
        expose: true
nn_genie_exploitation_delete_polyvalence:
    pattern: /delete-polyvalence/{id}
    defaults: { _controller: NNGenieExploitationBundle:Polyvalence:delete }
    options:
        expose: true
nn_genie_exploitation_edit_polyvalence:
    pattern: /edit-polyvalence/{id}
    defaults: { _controller: NNGenieExploitationBundle:Polyvalence:edit }
    options:
        expose: true
nn_genie_exploitation_add_personnel:
    path:     /new-personnel
    defaults: { _controller: NNGenieExploitationBundle:Personnel:add }
    options:
        expose: true
nn_genie_exploitation_view_personnel:
    pattern: /personnels
    defaults: { _controller: NNGenieExploitationBundle:Personnel:getAll }
    options:
        expose: true
nn_genie_exploitation_delete_personnel:
    pattern: /delete-polyvalence/{id}
    defaults: { _controller: NNGenieExploitationBundle:Personnel:delete }
    options:
        expose: true
nn_genie_exploitation_edit_personnel:
    pattern: /edit-personnel/{id}
    defaults: { _controller: NNGenieExploitationBundle:Personnel:edit }
    options:
        expose: true
nn_genie_exploitation_detail_personnel:
    pattern: /detail-personnel/{id}
    defaults: { _controller: NNGenieExploitationBundle:Personnel:detail }
    options:
        expose: true